@MovieStore.Api_HostAddress = http://localhost:5208

GET {{MovieStore.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET http://localhost:5208/movies

###
GET http://localhost:5208/genres

###
GET http://localhost:5208/movies/5

###
POST http://localhost:5208/movies
Content-Type: application/json
{
  "name" : "스파이더맨",
  "genreId" : 1,
  "price" : 4500,
  "releaseYear" : 2025 
}

###
PUT http://localhost:5208/movies/1
Content-Type: application/json
{
    "name": "돼지가 우물에 빠진날",
    "genreId": 1,
    "price": 5500,
    "releaseYear": 2025
  }

###
DELETE http://localhost:5208/movies/1